### ISSUE TITLE
Make d3-org-tree compatible with the latest version of d3

### ISSUE THREAD

**Issue by beune** [benyasin/d3-org-tree#4]
I noticed that `d3.event` [was removed in version 6 of `d3`](https://github.com/d3/d3/releases/tag/v6.0.0), and I believe this is also the cause for issue #3.

**Comment by benyasin** [comment]
> I noticed that `d3.event` [was removed in version 6 of `d3`](https://github.com/d3/d3/releases/tag/v6.0.0), and I believe this is also the cause for issue #3 

I have done it, thank you for your reminder
